  - name: Run Sensu Client container
    docker_container:
      name: "sensu-client"
      hostname: "sensu-client"
      image: "{{ sensu_client_image_name }}"
      state: started
      exposed_ports:
      - "3030:3030"
      volumes:
      - "{{ sensu_client_conf_path }}/config.json:{{ sensu_client_target_path }}/config.json"
      - "{{ sensu_client_conf_path }}/conf.d/client.json:{{ sensu_client_target_path }}/conf.d/client.json"
      - "/:/rootfs:ro"
